services:
  nexus:
    image: sonatype/nexus3
    restart: unless-stopped
    volumes:
      - ./data/nexus-data:/nexus-data
    ports:
      - "8000:8081"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
      - ./data/postgres-data:/var/lib/postgresql/data
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
